services:
  db:
    image: mysql:8.0
    container_name: mysql-nestjs-2025
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql_nestjs
    ports:
      - "3310:3306"

    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
